---
apiVersion: v1
kind: Service
metadata:
  name: k8s-server-load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: k8s-server-c
          imagePullPolicy: Never
          image: "localhost:5000/k8s-server-i"
          ports:
            - containerPort: 3000
...
